#ifndef __SCT_FSM_H__
#define __SCT_FSM_H__

/* Generated by fzmparser version 2.7 --- DO NOT EDIT! */

#include "SCT1_user.h"

extern void sct_fsm_init (void);

/* Output assignments (and their defaults if specified) */
#define sct_fsm_OUTPUT_AHI (0)
#define sct_fsm_OUTPUT_ALI (1)
#define sct_fsm_OUTPUT_BHI (5)
#define sct_fsm_OUTPUT_BLI (2)

#define sct_fsm_setOutputDefault() do {LPC_SCT1->OUTPUT = (LPC_SCT1->OUTPUT & ~0x00000000) | 0x00000000;} while(0)


/* Match register reload macro definitions */
#define sct_fsm_reload_AHI(value) do {LPC_SCT1->MATCHREL[0].U = value;} while(0)
#define sct_fsm_reload_ALI(value) do {LPC_SCT1->MATCHREL[1].U = value;} while(0)
#define sct_fsm_reload_BHI(value) do {LPC_SCT1->MATCHREL[2].U = value;} while(0)
#define sct_fsm_reload_BLI(value) do {LPC_SCT1->MATCHREL[3].U = value;} while(0)
#define sct_fsm_reload_MATCH_reset(value) do {LPC_SCT1->MATCHREL[4].U = value;} while(0)

#endif
